### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by amilajack**
- Fixes E2E tests (#2516 )
- Fixes preload entrypoint (#2503)

### CODE REVIEW

**Comment by leohxj** [comment]
hi, have a question, why downgrade electron to `7.1.13`?

**Comment by amilajack** [comment]
See https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2527#issue-454953236

**Comment by leohxj** [comment]
> See [#2527 (comment)](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2527#issue-454953236)

yes, I have the problem with redux devtools. Any plan to support electron@9?

**Comment by amilajack** [comment]
Yup. We will migrate to its once there's a solution for extensions

**Comment by leohxj** [comment]
Thanks, I will keep using electron@9. Hope the solution will fixed soon.

**Pull request merged**
