### PR TITLE
WIP: Feature/yarn pnp

### PR DESCRIPTION
**Pull request by kfp**
WIP PR to update config for yarn pnp.

After checkout:
```
yarn set version berry
yarn 
yarn
```

### CODE REVIEW

**Comment by kfp** [comment]
Presently seeing this error:
```
# This file contains the result of Yarn building a package (electron-react-boilerplate@workspace:.)
# Script name: postinstall

Internal Error: Unable to locate pnpapi, the module '.../electron-react-boilerplate/src/.pnp.js' is controlled by multiple pnpapi instances.
This is usually caused by using the global cache (enableGlobalCache: true)

Controlled by:
  .../electron-react-boilerplate/src/.pnp.js
  .../electron-react-boilerplate/.pnp.js
This is usually caused by using the global cache (enableGlobalCache: true)
```

I tried playing with cache settings but it didn't seem to make a difference

**Comment by merceyz** [comment]
You need to tell the root PnP to ignore the one in `src` using https://yarnpkg.com/configuration/yarnrc#pnpIgnorePatterns

**Comment by kfp** [comment]
Thanks, that fixed my error once I applied your workaround [here](https://github.com/yarnpkg/berry/issues/2470#issuecomment-777778172). Now I'm getting this (which I haven't spent any time investigating yet):

```
# This file contains the result of Yarn building a package (electron-react-boilerplate@workspace:.)
# Script name: postinstall

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
  • electron-builder  version=22.10.5
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=.../electron-react-boilerplate/src
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[BABEL] Note: The code generator has deoptimised the styling of .../electron-react-boilerplate/src/.pnp.js as it exceeds the max of 500KB.
[webpack-cli] RangeError: [BABEL] .../electron-react-boilerplate/src/.pnp.js: Maximum call stack size exceeded
```

**Comment by kfp** [comment]
Merged in richard-dp/master and now seeing:
```
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • electron-builder  version=22.10.5
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=.../electron-react-boilerplate/build/app
[BABEL] Note: The code generator has deoptimised the styling of .../electron-react-boilerplate/build/app/.pnp.js as it exceeds the max of 500KB.
[webpack-cli] Failed to load '.../electron-react-boilerplate/.erb/configs/webpack.config.renderer.dev.dll.babel.js' config
[webpack-cli] RangeError: Maximum call stack size exceeded
    at buildRootChain (.../electron-react-boilerplate/.yarn/cache/@babel-core-npm-7.14.0-87b08b8326-eccd8c6acf.zip/node_modules/@babel/core/lib/config/config-chain.js:141:28)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (.../electron-react-boilerplate/.yarn/cache/@babel-core-npm-7.14.0-87b08b8326-eccd8c6acf.zip/node_modules/@babel/core/lib/config/partial.js:85:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (.../electron-react-boilerplate/.yarn/cache/@babel-core-npm-7.14.0-87b08b8326-eccd8c6acf.zip/node_modules/@babel/core/lib/config/full.js:53:46)
    at loadFullConfig.next (<anonymous>)
    at Function.<anonymous> (.../electron-react-boilerplate/.yarn/cache/@babel-core-npm-7.14.0-87b08b8326-eccd8c6acf.zip/node_modules/@babel/core/lib/config/index.js:28:43)
    at Generator.next (<anonymous>)
    at evaluateSync (.../electron-react-boilerplate/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-d523437689.zip/node_modules/gensync/index.js:251:28)
    at Function.sync (.../electron-react-boilerplate/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-d523437689.zip/node_modules/gensync/index.js:89:14)

**Comment by kfp** [comment]
Pretty sure the stack size is coming from webpack.config.base.js
```
import { dependencies as externals } from '../../build/app/package.json';
```
Diving into what's going on here now.

**Comment by amilajack** [comment]
Closing this since the next version of electron-react-boilerplate will migrate to npm

**Pull request closed without merging**
