### PR TITLE
Web enablement: dev and prod

### PR DESCRIPTION
**Pull request by janakg**
Hi, PR for the "Publishing app to web & electron: Issue 80".

I have created a clean way to integrate web distribution and development. Please review the changes so we can close the long pending request from the community.

Thanks.

### CODE REVIEW

**Comment by janakg** [comment]
Hi people, anyone got a chance to review the changes?

**Comment by amilajack** [comment]
This is out of the scope of this project. We will, however, welcome adding this to our [examples repo](https://github.com/electron-react-boilerplate/examples). Please PR there

**Comment by janakg** [comment]
Sure, will see later.

**Comment by dbvrac** [comment]
@janakg This is very useful for me, though I realize it's beyond the scope of this project. I have some questions if you don't mind discussing it elsewhere.
Thanks!

**Pull request closed without merging**
