### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by amilajack**
- [x] Migrate to TypeScript from Flow ([#2363](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2363))
- [x] Use browserslist for `@babel/preset-env` targets ([#2368](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2368))
- [x] Use preload script, disable `nodeIntegration` in renderer process for [improved security](https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content) ([#2365](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2365))
- [x] Add support for azure pipelines ([#2369](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2369))
- [x] Disable sourcemaps in production
- [ ] Update site docs to reflect `v1.0.0` changes
- [ ] Drop support for Travis and Appveyor, GitHub Actions, move configs to docs

### Testing the Branch 
To test these changes run the following commands:
```bash
git clone https://github.com/electron-react-boilerplate/electron-react-boilerplate
cd electron-react-boilerplate
git checkout next
yarn
yarn test
```

### CODE REVIEW

**Comment by AElmoznino** [comment]
When are you merging @amilajack  😄?! Looking forward to this!

**Comment by amilajack** [comment]
I left this unmerged hoping to spread awareness about the changes and also to give myself some time to test this some more.

**Comment by AElmoznino** [comment]
Amazing, thank you so much and keep up the good work 👌🥳
What's your suggested way of migrating an existing ERB-project (like this for example: https://github.com/sveriges-utbildningsradio/ur-mobster)? I've removed redux and a ton of other dependencies.

**Comment by amilajack** [comment]
Adding a migration path would definitely be useful. For now I would suggest looking at the [file changes](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2370/files) and applying them to your codebase.

**Pull request merged**
