### PR TITLE
Fixed issue #3568 - updating electron version and make the app start

### PR DESCRIPTION
**Pull request by Maks19**
It should fix the [issue](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568) and be compatible with older Electron versions.
Most of the changes have been taken from the issue conversation. (https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568#issuecomment-1978225949, https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568#issuecomment-1980507893, https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568#issuecomment-2052729272)
@slhck @1111mp @ifree92

### CODE REVIEW

**Comment by rossicler-hostalky** [comment]
I started using this but sometimes I'm having an issue related to reloading the main process, where electronmon fails to reload and app just keeps hanging. Even by terminating the terminal process, it still doesn't close the app. I'm only able to close the app through macOS "Force Quit", which then shows me in the terminal that electromon was closed.

**Comment by Maks19** [comment]
> I started using this but sometimes I'm having an issue related to reloading the main process, where electronmon fails to reload and app just keeps hanging. Even by terminating the terminal process, it still doesn't close the app. I'm only able to close the app through macOS "Force Quit", which then shows me in the terminal that electromon was closed.

I didn't experience such an issue. Could you please provide some repo or sandbox to test it? If it's not possible, have you noticed any special conditions when this happens?

**Comment by rossicler-hostalky** [comment]
> > I started using this but sometimes I'm having an issue related to reloading the main process, where electronmon fails to reload and app just keeps hanging. Even by terminating the terminal process, it still doesn't close the app. I'm only able to close the app through macOS "Force Quit", which then shows me in the terminal that electromon was closed.
> 
> I didn't experience such an issue. Could you please provide some repo or sandbox to test it? If it's not possible, have you noticed any special conditions when this happens?

Unfortunately I can't share the code of the repo, so I tried reproducing with a fresh project, but it works as expected. It's probably something related to specific libraries used in my project, or some configuration changes done.

The main issue for finding out the issue is that there's no relevant logs, all I get is this:

After changing any file under `main/`
```bash
[1] [electronmon] renderer file change: src/main/main.ts
[1] [electronmon] main file change: .erb/dll/main.bundle.dev.js
```

Changes are detected as expected, but the app doesn't restart, and if I try to close the terminal process, I get this:
```bash
[0] cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --watch --config ./.erb/configs/webpack.config.main.dev.ts exited with code 0
--> Sending SIGTERM to other processes..
```
But nothing happens, so I need to manually go to maOS force quit and close the electron application.

**Comment by sytolk** [comment]
@rossicler-hostalky if you skip electronmon to watch for changes in  ".erb/dll/**" -> look in package.json This change fix double reload of app on starting for me

**Comment by rossicler-hostalky** [comment]
> @rossicler-hostalky try to skip electronmon to watch for changes in ".erb/dll/**" -> look in package.json Removing this line fix double reload of app on starting for me

Unfortunately that does not fix the issue for me, it just "mask" the issue by not reloading the main process, but if I try to finish the process it still fails to terminate and I have to use Force Quit to close the app.

**Comment by amilajack** [comment]
> I'm having an issue related to reloading the main process, where electronmon fails to reload and app just keeps hanging

@rossicler-hostalky I'm unable to repro this locally as well but let me know if you're still running into any other issues 

I've tested this locally. I'm going to go ahead and merge here

**Comment by rossicler-hostalky** [comment]
> > I'm having an issue related to reloading the main process, where electronmon fails to reload and app just keeps hanging
> 
> @rossicler-hostalky I'm unable to repro this locally as well but let me know if you're still running into any other issues
> 
> I've tested this locally. I'm going to go ahead and merge here

@amilajack for sure, I didn't had the time to actively work on this yet, but if I'm able to find the root cause and/or fix it, I'll share here in case someone else go through the same issue.

**Comment by sytolk** [comment]
This issue appears if you have https://github.com/withcatai/node-llama-cpp dependency in root package json (or releases/app/package.json). There is sample electron project with `vite` that works: https://github.com/withcatai/node-llama-cpp/tree/master/templates/electron-typescript-react
How can node-llama-cpp works with electron-react-boilerplate?

**Pull request merged**
