### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by amilajack**
- [x] drop redux
- [x] remove counter example app
- [x] simplify directory structure
- [x] move `dll` dir to `.erb` dir
- [x] fix icon/font import paths
- [x] migrate to `react-refresh` from `react-hot-loader`
- [x] migrate to webpack@5
- [x] migrate to electron@11
- [x] remove e2e tests and testcafe integration
- [x] rename `app` dir to more conventional `src` dir
- [x] rename `resources` dir to `assets`
- [x] simplify npm scripts 
- [x] drop stylelint
- [x] simplify styling of boilerplate app
- [x] remove `START_HOT` env variable
- [x] notarize support
- [x] landing page boilerplate
- [x] docs updates
- [x] restore removed debugging support

### CODE REVIEW

**Comment by arinhouck** [comment]
Hey @amilajack, just wanted to share. I am experiencing some issues installing node-gyp related packages like `web3` on this branch but works fine on master.

I downgraded back to `"electron-rebuild": "^1.10.0",` and had no issues now. 

Looking forward to this release!

**Comment by amilajack** [comment]
What's your stacktrace?

**Comment by ivanms1** [comment]
@arinhouck Hello, just wondering if you managed to solve your issue, I think I am experiencing something similar.

**Comment by Hidenaga41** [comment]
> Hey @amilajack, just wanted to share. I am experiencing some issues installing node-gyp related packages like `web3` on this branch but works fine on master.
> 
> I downgraded back to `"electron-rebuild": "^1.10.0",` and had no issues now.

I faced the same problem, but I solved it by downgrading as well.
Thank you！

**Pull request merged**
