### PR TITLE
Loading routes using React.lazy

### LINKED ISSUE #1888: PR: Lazy load routes using React.lazy
https://twitter.com/TheLarkInn/status/1056729742437543936
https://github.com/reactjs/rfcs/blob/gaearon-patch-2/text/0000-lazy.md

### PR DESCRIPTION
**Pull request by fxnoob**
Closes #1888

### CODE REVIEW

**Comment by amilajack** [comment]
I think a nice addition to this would be eagerly loading the HomePage and lazily loading the CounterPage. I'm assuming the current implementation has a flash of content. Is that true?

**Comment by fxnoob** [comment]
Oh, yes. Current implementation has a flash of content.

**Comment by fxnoob** [comment]
Hi @amilajack. It still has a flash of content. How can I resolve this?

**Comment by amilajack** [comment]
I'm not sure because I haven't used these features before.

**Comment by fxnoob** [comment]
Hi @amilajack , 'flash of content' problem only occurring in dev mode as css is bundled with js and that is loaded dynamically. In prod mode 'mini-css-extract-plugin' plugin is use. So there will be no such problem in prod mode.

**Pull request closed without merging**
