### PR TITLE
Enable web: dev and build

### PR DESCRIPTION
**Pull request by rntjr**
This PR is an update to version 1.3.0 of PR #2136 and issue #80.
Dev and build webpacks for the web are configured for typescript, working perfectly.

Need for someone else to validate.

### CODE REVIEW

**Comment by rntjr** [comment]
Lockfile fixed.

**Comment by jooohhn** [comment]
Thanks for the PR! My initial thoughts:

Pros:
- Benefits many users since many electron-based apps also have a web version

Cons: 
- Would add complexity to maintaining ERB
- Would add unnecessary bloat for users that don't need it

IMO the last con is particularly important. There's a lot of interest for putting user configurations over project convention (#2476, #2512)

In the case where this PR isn't merged, I strongly think that the content should still be incorporated into the ERB docs since

**Comment by rntjr** [comment]
In fact, maintenance is very complex, especially on large projects.
I am analyzing to develop an ERP tool having a central server and also private servers of the clients themselves. The main problem that is making me abandon Electron for this project is that, whenever there is a private server, I will have to do a different build for it.
But in applications that have a central server it has great usability.

**Comment by barrynorman** [comment]
Is this still working? I was wondering how apps like slack are building a web version. thanks

**Comment by Unforgiven-wanda** [comment]
Any update for getting this to work on the latest boilerplate version?

**Pull request closed without merging**
