### PR TITLE
IPC example from main to renderer with renderer.d.ts

### PR DESCRIPTION
**Pull request by paragbaxi**

### CODE REVIEW

**Review by UserJHansen — CHANGES_REQUESTED** [review]
There should be an empty dependency array for the useEffect to prevent it re-running

**Comment by paragbaxi** [comment]
i can't edit the commit. need to add `import { useEffect } from 'react';` to App.tsx

**Comment by paragbaxi** [comment]
added main.ts sending

**Comment by UserJHansen** [comment]
lgtm, can we get a workflow run?

**Comment by amilajack** [comment]
Thanks for the PR. While I think this is a geat example, I'm hesitant when adding further complexity to the boilerplate example. Instead what we should do is provide an example in the docs. To get started, you can PR a md file to the [docs](https://github.com/electron-react-boilerplate/site/tree/main/docs).

**Pull request closed without merging**
