### PR TITLE
Generate all other required icons from single icon.png in resource folder 

### PR DESCRIPTION
**Pull request by arslanmughal99**
With this commit you will able to generate all other icons required in `resources` directory from single `icon.png` using script `yarn gen:icons`

### CODE REVIEW

**Comment by amilajack** [comment]
Where is the source for the generated binary files in the `bin` directory?

**Comment by arslanmughal99** [comment]
Check these out 
https://github.com/arslanmughal99/erb-assets-generator
https://github.com/arslanmughal99/erb-icons-gen

may be this is not the perfect fit but my point here is to give an idea , Because it is very painful to generate icons each time there is small change from designers team. So there must b some script that generate all icons automatically from single icon.png

**Comment by arslanmughal99** [comment]
The binary is written in Golang

**Comment by amilajack** [comment]
I see. Thanks for creating a PR for this. Ideally the tool could be written in node so that developers could take tweak the tool if necessary. Do you know of any node equivalents?

**Comment by arslanmughal99** [comment]
Yes i think it is possible with [Jimp](https://www.npmjs.com/package/jimp) but i dont know well Jimp will perform .

**Comment by amilajack** [comment]
I think I'd prefer erb-generate using jimp here since. Closing this in favor of a PR that generates icons from jimp

**Comment by arslanmughal99** [comment]
Check [electron-icon-builder](https://www.npmjs.com/package/electron-icon-builder) . This looks more promising to me only you need to change folder structure a little for resources .

**Comment by arslanmughal99** [comment]
i am working on new package and i will update you today 👍

**Comment by arslanmughal99** [comment]
Checkout this one i have removed binaries, [erb-icons-gen](https://github.com/arslanmughal99/erb-icons-gen)

**Comment by amilajack** [comment]
This package seems to have good community support:
https://github.com/jaretburkett/electron-icon-maker

I would prefer to use this library since it seems. What are your thoughts on this?

**Comment by arslanmughal99** [comment]
Yes if you think this works best then you can continue with `electron-icon-maker` , However this feature is optional and does not required any active community to maintain and using `electron-icon-maker` will make folder structure verbose .

**Comment by arslanmughal99** [comment]
Any updates on this ?

**Comment by amilajack** [comment]
It seems like electron-icon-maker seems like the road forward. Closing in favor of a PR for integrating with it.

**Pull request closed without merging**
