### PR TITLE
[WIP]: add initial electron-redux support

### PR DESCRIPTION
**Pull request by amilajack**
Closes https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1920

- [x] Add initial implementation
- [ ] Add example of usage

### CODE REVIEW

**Comment by vandosant** [comment]
Is this still active? I tried implementing your changes in my application, but I'm getting `Could not find reduxState global in main process, did you forget to call replayActionMain?` -- hoping to see an example usage! Thanks.

**Comment by amilajack** [comment]
Haven't had time to finish it

**Comment by amilajack** [comment]
Haven't spent much time on this because I didn't know if there would be any demand for it. I'll take another look soon. Sorry for the delay on this. Currently busy maintaining other projects ATM

**Comment by Slapbox** [comment]
@amilajack you're one of the busiest folks I know on GitHub, and I and others appreciate all you do! I'm pretty sure the issue here is as simple as changing this line (though I've not tested it outside my own project):

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/0b681c3adff664d7a694752ab3fb803be15104f0/app/store/configureStore.dev.js#L59

The issue is that a property of `window` is being checked before we check if it's the `renderer` process/before we check if `window` is defined.

```js
const composeEnhancers = scope === 'renderer' && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
```

**Comment by amilajack** [comment]
@Slapbox I see. So should we move that line to be before https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/0b681c3adff664d7a694752ab3fb803be15104f0/app/store/configureStore.dev.js#L43?

**Comment by Slapbox** [comment]
@amilajack I think if we do that then `composeEnhancers` will not be defined, as opposed to toggling between `__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` and Redux's built in `compose`.

I'm not sure of any way to submit a PR on a PR, so here's a gist with more or less what I did: https://gist.github.com/Slapbox/a169953ad477cde04a6be53844b0a0dd#file-js-L59

----

Unrelated to getting it working, once this is added it's important we note the importance of having a `payload` property in your actions. Despite not being required in Flux Standard Actions, Electron-Redux will not relay actions missing a `payload` property.

**Comment by amilajack** [comment]
@Slapbox you can PR to my branch. I think that would be the best way to suggest changes. That way we can also check if CI passes when you PR to my branch

**Comment by NclsL** [comment]
A bit late, but I implemented the changes above and the issue stayed. Shouldn't we do
```
import { configureStore } from './store/configureStore';
const store = configureStore(undefined, 'main');
```

in `app/main.dev.js`

or something similar? 
I tried adding those and it only led to another issue that I was unable to solve:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Invariant Violation: Hash history needs a DOM
    at invariant (/home/x/Projects/electron-react-boilerplate/node_modules/invariant/invariant.js:40:15)
    at createHashHistory (/home/x/Projects/electron-react-boilerplate/node_modules/history/createHashHistory.js:69:27)
    at Object.<anonymous> (/home/x/Projects/electron-react-boilerplate/app/store/configureStore.dev.js:17:17)
    at Object.<anonymous> (/home/x/Projects/electron-react-boilerplate/app/store/configureStore.dev.js:122:3)
    at Module._compile (module.js:642:30)
    at Module._compile (/home/x/Projects/electron-react-boilerplate/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:653:10)
    at Object.newLoader [as .js] (/home/x/Projects/electron-react-boilerplate/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
```

**Comment by Slapbox** [comment]
I got this working in my project, but I don't use routing. I originally got stuck in the same place as @NclsL when I included routing. Does anyone have any thoughts on working around that? It's never going to make it into the master branch if we can't get it working with routing.

**Pull request closed without merging**
