### PR TITLE
Updated electron 9.0.0

### PR DESCRIPTION
**Pull request by null-none**

### CODE REVIEW

**Comment by johnstew** [comment]
This should get merged in otherwise you get errors that are only solvable by upgrading on your own.

**Comment by johnstew** [comment]
On second thought, I'm not sure we want to delete the yarn.lock

**Comment by null-none** [comment]
@johnstew about `yarn.lock` ok

**Comment by DmitryMK** [comment]
This update does not allow to use react/redux devtools.

**Pull request closed without merging**
